tmart/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

from .views import  Home
from Documentation.views import DocsList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view() , name = 'Home'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('docs/' , include('Documentation.urls')),
    path('', include('tmart_Product.urls')),
    path('', include('tmart_account.urls')),
    path('', include('tmart_settings.urls')),
    path('', include('tmart_Cart_and_Favorite.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

from .API_views import *
# REST-APIS
urlpatterns+=[
    path('product_price_range' , SingleProductPriceRangeAPI.as_view()),
    path('all_products' , AllSingleProducts.as_view()),
    path('all_products/<int:pk>' , SpecificSingleProducts.as_view()),
    path('single_products_by_set/<int:set_id>' , SingleProductsBySet.as_view()),
    path('single_products_by_colors/<color>' , SingleProductsByColors.as_view()),
    path('most_viewed_products' , MostViewedSingleProducts.as_view()),
    path('single_products_by_tags/<tag>' , SingleProductsByTags.as_view()),

    path('single_products_high_price' , SingleProducts_HighPrice.as_view()),
    path('single_products_low_price' , SingleProducts_LowPrice.as_view()),
    path('single_products_with_discount' , SingleProducts_WithDiscount.as_view()),


]

if settings.DEBUG:
    urlpatterns=urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tmart_Product/urls.py
from django.urls import path
from tmart_Product.views import (
    AllProducts,
    ProductSearch,
    SelectedSet,
    ProductDetail,
    AllProductsBy_SubCategory,
    SelectedCategory,
)
# REST
app_name = 'tmart_Product'
urlpatterns = [
    path('set/' , AllProducts.as_view() , name = 'AllProducts'),
    path('set/<int:id>' , SelectedSet.as_view() , name = 'set_with_id'),
    path('category/<int:id>' , SelectedCategory.as_view() , name = 'category_with_id'),
    path('search' , ProductSearch.as_view() , name = 'search'),
    path('ProductDetail/<slug>' , ProductDetail , name = 'ProductDetail'),
    path('subcategory/<int:id>' , AllProductsBy_SubCategory.as_view() , name = 'SubCategory'),
]

tmart_Product/models.py
from enum import unique
from django.db import models
from django.db.models import Q
from ckeditor.fields import RichTextField
from django.db.models.signals import pre_save
from tmart.utils import unique_slug_generator
from django.utils.html import format_html
from django.contrib.auth.models import User
from django.forms import ModelForm

from tmart_settings.models import IPs
# Create your models here.

class ProductManager(models.Manager):
    def search(self,query):
            lookup = (
            Q(title__icontains=query) | 
            Q(set__title_fa__icontains=query) |
            Q(tags__name__icontains=query)
            )
            return self.get_queryset().filter(lookup).distinct()
            
    def get_by_slug(self,slug):
        qs = SingleProduct.objects.get_queryset().filter(slug=slug)
        if qs.count()==1:
            return qs.first()

class Category(models.Model):
    name = models.CharField(max_length=100 , verbose_name='نام دسته بندی')
    description = RichTextField(default = 'Description')
    hot_subcategory_banner = models.ImageField(default = 'empty',upload_to = 'hot_suggestions',null = True , blank = True)
    def __str__(self) :
        return self.name

    def get_absolute_url(self):
        return f"category/{self.id}"

class SubCategory(models.Model):
    category = models.ForeignKey(Category , on_delete=models.CASCADE , null=True , blank=True, related_name="subcategory")
    title_fa = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100 , blank = True , null = True)

    def __str__(self) :
        return self.title_fa

    def get_absolute_url(self):
        return f"subcategory/{self.id}"

class Set(models.Model):
    subcategory = models.ForeignKey(SubCategory , on_delete=models.CASCADE , null=True , blank=True, related_name="set")
    title_fa = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100 , blank = True , null = True)
    hot_subcategory_banner = models.ImageField(default = 'empty',upload_to = 'hot_suggestions',null = True , blank = True)

    def get_absolute_url(self):
        return f"set/{self.id}"

    def __str__(self) :
        return self.title_fa

class Tags(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Colors(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100)

    def color_tag(self):
        if self.code is not None:
            return format_html('<p style="background-color:{};color:white;padding:10px;border-radius:25%;width:20px"></p>'.format(self.code))
        else:
            return ""

    def __str__(self):
        return self.name

class SingleProduct(models.Model):
    set = models.ForeignKey(Set , on_delete=models.CASCADE,blank = True , null = True)
    title = models.CharField(max_length=250 , blank = True , null = True)
    description = RichTextField(blank = True , null = True)
    features = models.TextField(blank = True , null = True)
    image = models.ImageField(null = True,blank = True,upload_to = 'SingleProducts_Cover/' , default = 'static/product_images/category_1.jpg')
    slug = models.SlugField(max_length=100,unique=True,blank=True,allow_unicode=True , null=True)
    price = models.IntegerField(default=0,blank = True , null = True)
    tags = models.ManyToManyField(Tags,blank = True)
    colors = models.ManyToManyField(Colors , blank=True)
    discount = models.IntegerField(default='0',blank = True , null = True)
    count = models.IntegerField(default=0)
    available = models.BooleanField(default = False)
    hits = models.ManyToManyField(IPs , blank=True )
    hot_offer = models.BooleanField(default = False)
    objects = ProductManager()


    def image_tag(self):
        return format_html('<img src="{}" / style="width:70px;">'.format(self.image.url))

    image_tag.short_description = 'Image'

    def price_with_discount(self):
        if self.price - self.discount > 0 :
            return self.price - self.discount
        else:
            return "مقدار تخفیف بیشتر از قیمت کالا می باشد"

    def get_absolute_url(self):
        return f"/ProductDetail/{self.slug}"


def product_presave_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
pre_save.connect(product_presave_receiver,sender=SingleProduct)

class singleProductGallery(models.Model):
    name    = models.CharField(max_length=200)
    image   = models.ImageField()
    product = models.ForeignKey(SingleProduct,on_delete=models.CASCADE,related_name='aaa')

    def __str__(self) :
        return self.name

class Review(models.Model):
    STATUS= (
    ('wating_for_published','در انتظار تایید'),
    ('True' , 'تایید شده'),
    ('False', 'تایید نشده')
    )
    product = models.ForeignKey(SingleProduct,on_delete = models.CASCADE)
    user    = models.ForeignKey(User,on_delete = models.CASCADE)
    comment = models.TextField()
    status  = models.CharField(max_length=20,choices=STATUS,default='wating_for_published')
    create_at= models.DateField(auto_now_add = True)

    def __str__(self) :
        return self.user.first_name
class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['product', 'user'  ,'comment']

tmart_Product/forms.py
from django import forms
from .models import Review
class ReviewForm(forms.Form):
    class Meta:
        model = Review
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder':'متن نظر'}),
    )

tmart_Product/views.py
from django.shortcuts import render
from django.views.generic import ListView , DetailView
from .models import SingleProduct , singleProductGallery ,IPs ,Set,Review , Category
from .forms import ReviewForm
from django.contrib.auth.models import User
from tmart_account.signals import user_product_view
# Create your views here.

class AllProducts(ListView):
    template_name = 'Products_templates/shop.html'
    paginate_by = 8
    def get_queryset(self):
        return SingleProduct.objects.filter(available = True)

class AllProductsBy_SubCategory(ListView):
    template_name = 'Products_templates/shop.html'
    paginate_by = 8
    def get_queryset(self):
        return SingleProduct.objects.filter(set__subcategory_id = self.kwargs['id'])

class SelectedSet(ListView):
    template_name = 'Products_templates/shop.html'
    paginate_by = 8

    def get_queryset(self):
        return SingleProduct.objects.filter(set_id = self.kwargs['id'])

class SelectedCategory(ListView):
    template_name = 'Products_templates/shop_ByCategory.html'
    paginate_by = 8

    def get_queryset(self):
        return SingleProduct.objects.filter(set__subcategory__category_id = self.kwargs['id'])



class ProductSearch(ListView):
    template_name =  'Products_templates/shop.html'
    paginate_by = 8

    def get_queryset(self):
        request = self.request
        print(request.GET)
        our_query = request.GET.get('q')
        if our_query is not None:
            return SingleProduct.objects.search(our_query)
        return SingleProduct.objects.all()


def ProductDetail(request, slug):
    try:
        object = SingleProduct.objects.get(slug = slug)
    except:
        object = None

    if request.user.is_authenticated:
        user_product_view(object.id , request.user)
    if object.features:
        features = object.features.split(',')
    features = None

    try:
        category = Category.objects.get(subcategory__set__singleproduct = object)
    except Category.DoesNotExist:
        category = None

    review_form = None
    if request.user.is_authenticated:
        if not Review.objects.filter(product = object , user = request.user).exists():
            review_form = ReviewForm(request.POST or None)
            if review_form.is_valid():
                comment = review_form.cleaned_data.get('comment')
                user = request.user
                Review.objects.create(product = object , user = user , comment = comment)
                review_form = None


    context = {
    'gallery'    : singleProductGallery.objects.filter(product=object),
    'features'   :features,
    'review_form':review_form,
    'all_reviews':Review.objects.filter(product = object),
    'related'    :SingleProduct.objects.filter(tags__singleproduct = object).exclude(id = object.id).distinct()[:10],
    'category'   :category,
    'object':object
    }
    return render(request , 'Products_templates/ProductDetail.html' , context)

tmart_Product/templates/Products_templates/favorite_products_component.html
{% load ratings %}                 
                            <div class="col-md-3 single__pro col-lg-3 cat--1 col-sm-4 col-xs-12">
                                <div class="product foo">
                                    <div class="product__inner">
                                        <div class="pro__thumb">
                                            <a href="#">
                                                <img src="{{item.product.image.url}}" alt="product images" height="250px">
                                            </a>
                                        </div>
                                        <div class="product__hover__info">
                                            <ul class="product__action">
                                                <li><a data-toggle="modal" data-target="#productModal{{item.product.id}}" title="Quick View" class="quick-view modal-view detail-link" href="#"><span class="ti-plus"></span></a></li>
                                                <li><a title="Add TO Cart" href="cart.html"><span class="ti-shopping-cart"></span></a></li>
                                                <li><a title="Wishlist" href="delete_favorite/{{item.id}}"><span class="">x</span></a></li>
                                            </ul>
                                        </div>
                                    </div>

                                    <div class="product__details">
                                        {% ratings item %}
                                        <h2 class=""><a href="{{get_absolute_url}}">{{item.product.title | truncatewords:5}}</a></h2>

                                        <ul class="product__price">
                                            <li class="old__price">{{item.product.price_with_discount}}</li>
                                            <li class="new__price">{{item.product.price}}</li>
                                        </ul>

                                    </div>
                                </div>
                            </div>

{% include 'Products_templates/quick_view_favorite.html' %}

tmart_Product/templates/Products_templates/filter_menu.html
<div class="filter__wrap">
                        <div class="filter__cart">
                            <div class="filter__cart__inner">
                                <div class="filter__menu__close__btn">
                                    <a href="#"><i class="zmdi zmdi-close"></i></a>
                                </div>
                                <div class="filter__content">
                                    <!-- Start Single Content -->
                                    <div class="fiter__content__inner text-right">
                                        <div class="single__filter">
                                            <h4 class="rtl">مرتب کردن بر اساس :</h4>
                                            <hr>
                                            <ul class="filter__list">
                                                {% for filters in filters %}
                                                <li><a href="#default">{{filters}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        <!--<div class="single__filter">
                                            <h2>Size</h2>
                                            <ul class="filter__list">
                                                <li><a href="#xxl">XXL</a></li>
                                                <li><a href="#xl">XL</a></li>
                                                <li><a href="#x">X</a></li>
                                                <li><a href="#l">L</a></li>
                                                <li><a href="#m">M</a></li>
                                                <li><a href="#s">S</a></li>
                                            </ul>
                                        </div>-->
                                        <div class="single__filter text-right">
                                            <h4 class="rtl">برچسب ها :</h4>
                                            <hr>
                                            <ul class="filter__list">
                                                {% for tag in tags %}
                                                <li><a href="#">{{tag}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        <div class="single__filter text-right">
                                            <h4 class="rtl">قیمت ها :</h4>
                                            <hr>
                                            <ul class="filter__list">
                                                <li><a href="#">$0.00 - $50.00</a></li>
                                                <li><a href="#">$50.00 - $100.00</a></li>
                                                <li><a href="#">$100.00 - $150.00</a></li>
                                                <li><a href="#">$150.00 - $200.00</a></li>
                                                <li><a href="#">$300.00 - $500.00</a></li>
                                                <li><a href="#">$500.00 - $700.00</a></li>
                                            </ul>
                                        </div>
                                        <div class="single__filter">
                                            <h4>بر اسا رنگبندی</h4>
                                            <hr>
                                            <ul class="filter__list sidebar__list text-right">
                                                {% for color in colors %}
                                                    <li class="black"><a href="#">{{color}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                    <!-- End Single Content -->
                                </div>
                            </div>
                        </div>
                    </div>

tmart_Product/templates/Products_templates/product_component.html
{% load ratings %}                 
                            <div class="col-md-3 single__pro col-lg-3 cat--1 col-sm-4 col-xs-12">
                                <div class="product foo">
                                    <div class="product__inner">
                                        <div class="pro__thumb">
                                            <a href="{{item.get_absolute_url}}">
                                                <img src="{{item.image.url}}" alt="product images" height="250px">
                                            </a>
                                        </div>
                                        <div class="product__hover__info">
                                            <ul class="product__action">
                                                <li><a data-toggle="modal" data-target="#productModal{{item.id}}" title="Quick View" class="quick-view modal-view detail-link" href="#"><span class="ti-plus"></span></a></li>
                                                <li><a title="Wishlist" href="{% url 'add_to_favorite' slug=item.slug %}"><span class="ti-heart"></span></a></li>
                                            </ul>
                                        </div>
                                    </div>

                                    <div class="product__details">
                                        
                                        <h2 class=""><a href="{{item.get_absolute_url}}">{{item.title | truncatewords:5}}</a></h2>

                                        <ul class="product__price">
                                            <li class="old__price">{{item.price_with_discount}}</li>
                                            <li class="new__price">{{item.price}}</li>
                                        </ul>

                                    </div>
                                </div>
                            </div>
{% include 'Products_templates/quick_view.html' %}

tmart_Product/templates/Products_templates/quick_view.html
                    <div id="quickview-wrapper">
        <!-- Modal -->
        <div class="modal fade" id="productModal{{item.id}}" tabindex="-1" role="dialog">
            <div class="modal-dialog modal__container" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <div class="modal-product">
                            <!-- Start product images -->
                            <div class="product-images">
                                <div class="main-image images">
                                    <img alt="big images" src="{{item.image.url}}" width="600px" height="600px">
                                </div>
                            </div>
                            <!-- end product images -->
                            <div class="product-info">
                                <h1 class="rtl">{{item.title}}</h1>
                                <div class="price-box-3">
                                    <div class="s-price-box">
                                        <span class="new-price">{{item.price_with_discount}}</span>
                                        <span class="old-price">{{item.price}}</span>
                                    </div>
                                </div>
                                <div class="quick-desc rtl">
                                    {{item.description|truncatewords:25|safe}}
                                </div>

                                <div class="addtocart-btn">
                                    <a href="{% url 'tmart_Product:ProductDetail' slug=item.slug %}">مشاهده با جزئیات کامل</a>
                                </div>
                            </div><!-- .product-info -->
                        </div><!-- .modal-product -->
                    </div><!-- .modal-body -->
                </div><!-- .modal-content -->
            </div><!-- .modal-dialog -->
        </div>
        <!-- END Modal -->
    </div>

tmart_Product/templates/Products_templates/shop.html
{% extends 'Base.html' %}
{% load static %}
{% load settings_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="bradcaump__inner text-right rtl">
                    <nav class="bradcaump-inner">
                      <a class="breadcrumb-item" href="{% url 'Home' %}">خانه</a>
                      <span class="brd-separetor">/</span>
                      <a class="breadcrumb-item" href="{% url 'tmart_Product:AllProducts' %}">محصولات</a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
        <!-- End Bradcaump area --> 
        <!-- Start Our Product Area -->
        <section class="htc__product__area shop__page ptb--130 bg__white">
            <div class="container">
                <div class="htc__product__container">
                    <!-- Start Product MEnu -->
                    <div class="row">
                        <div class="col-md-12 rtl">
                            <div class="filter__menu__container">
                                <!--<div class="product__menu">
                                    <button data-filter="*"  class="is-checked">All</button>
                                    <button data-filter=".cat--1">Furnitures</button>
                                    <button data-filter=".cat--2">Bags</button>
                                    <button data-filter=".cat--3">Decoration</button>
                                    <button data-filter=".cat--4">Accessories</button>
                                </div>-->
                                <div class="filter__box">
                                    <a class="filter__menu" href="#">فیلترها</a>
                                </div>

                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- Start Filter Menu -->
                    {% filter_menu %}
                    <!-- End Filter Menu -->
                    <!-- End Product MEnu -->
                    <div class="row">
                        <div class="product__list another-product-style">
                            {% if page_obj|length > 0 %}
                            <!-- Start Single Product -->
                            {% for item in page_obj %}
                                {% include 'products_templates/product_component.html' %}
                            {% endfor %}
                            <!-- End Single Product -->
                            {% else %}
                            <h3 class="alert alert-warning">هنوز محصولی به این دسته بندی اضافه نشده</h3>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <hr>
                {% if page_obj|length > 0 %}
                        <nav aria-label="...">
                          <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class=""><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                            {% endif %}

                            {% for page in paginator.page_range %}
                            {% if page == page_obj.number%}
                                <li class="active"><a href="?page={{page}}">{{page}} <span class="sr-only">(current)</span></a></li>
                            {% else %}
                                <li class=""><a href="?page={{page}}">{{page}} <span class="sr-only">(current)</span></a></li>
                            {% endif %}
                            {% endfor %}
                            
                            {% if page_obj.has_next %}
                            <li class=""><a href="?page={{ page_obj.next_page_number }}" aria-label="Nexts"><span aria-hidden="true">&raquo;</span></a></li>
                            {% endif %}
                          </ul>
                        </nav>
                {% endif %}
            </div>
        </section>
        <!-- End Our Product Area -->
    </div>
    <!-- Body main wrapper end -->
    <!-- QUICKVIEW PRODUCT -->

{% endblock %}

tmart_Product/templates/Products_templates/shop_ByCategory.html
{% extends 'Base.html' %}
{% load static %}
{% load settings_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="bradcaump__inner text-right rtl">
                    <nav class="bradcaump-inner">
                      <a class="breadcrumb-item" href="{% url 'Home' %}">خانه</a>
                      <span class="brd-separetor">/</span>
                      <a class="breadcrumb-item" href="{% url 'tmart_Product:AllProducts' %}">محصولات</a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
        <!-- End Bradcaump area --> 
        <!-- Start Our Product Area -->
        <section class="htc__product__area shop__page ptb--130 bg__white">
            <div class="container">
                <div class="htc__product__container">
                    <!-- Start Product MEnu -->
                    <div class="row rtl">
                        <div class="col-md-12">
                            <div class="filter__menu__container">
                                <!--<div class="product__menu">
                                    <button data-filter="*"  class="is-checked">All</button>
                                    <button data-filter=".cat--1">Furnitures</button>
                                    <button data-filter=".cat--2">Bags</button>
                                    <button data-filter=".cat--3">Decoration</button>
                                    <button data-filter=".cat--4">Accessories</button>
                                </div>-->
                                <div class="filter__box">
                                    <a class="filter__menu" href="#">فیلترها</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- Start Filter Menu -->
                    {% filter_menu %}
                    <!-- End Filter Menu -->
                    <!-- End Product MEnu -->
                    <div class="row">
                        <div class="product__list another-product-style">
                            {% if page_obj|length > 0 %}
                            <!-- Start Single Product -->
                            {% for item in page_obj %}
                                {% include 'Products_templates/product_component.html' %}
                            {% endfor %}
                            <!-- End Single Product -->
                            {% else %}
                            <h5 class="alert alert-warning text-center">هنوز محصولی به این دسته بندی اضافه نشده</h5>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <hr>
                {% if page_obj|length > 0 %}
                    	<nav aria-label="...">
						  <ul class="pagination">
						  	{% if page_obj.has_previous %}
						    <li class=""><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
						    {% endif %}

						    {% for page in paginator.page_range %}
						    {% if page == page_obj.number%}
						    	<li class="active"><a href="?page={{page}}">{{page}} <span class="sr-only">(current)</span></a></li>
						    {% else %}
						    	<li class=""><a href="?page={{page}}">{{page}} <span class="sr-only">(current)</span></a></li>
						    {% endif %}
	                        {% endfor %}
						    
						    {% if page_obj.has_next %}
						    <li class=""><a href="?page={{ page_obj.next_page_number }}" aria-label="Nexts"><span aria-hidden="true">&raquo;</span></a></li>
						    {% endif %}
						  </ul>
						</nav>
                {% endif %}

            </div>
        </section>
        <!-- End Our Product Area -->
    </div>
    <!-- Body main wrapper end -->
    <!-- QUICKVIEW PRODUCT -->

{% endblock %}