tmart/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

from .views import  Home
from Documentation.views import DocsList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view() , name = 'Home'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('docs/' , include('Documentation.urls')),
    path('', include('tmart_Product.urls')),
    path('', include('tmart_account.urls')),
    path('', include('tmart_settings.urls')),
    path('', include('tmart_Cart_and_Favorite.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

from .API_views import *
# REST-APIS
urlpatterns+=[
    path('product_price_range' , SingleProductPriceRangeAPI.as_view()),
    path('all_products' , AllSingleProducts.as_view()),
    path('all_products/<int:pk>' , SpecificSingleProducts.as_view()),
    path('single_products_by_set/<int:set_id>' , SingleProductsBySet.as_view()),
    path('single_products_by_colors/<color>' , SingleProductsByColors.as_view()),
    path('most_viewed_products' , MostViewedSingleProducts.as_view()),
    path('single_products_by_tags/<tag>' , SingleProductsByTags.as_view()),

    path('single_products_high_price' , SingleProducts_HighPrice.as_view()),
    path('single_products_low_price' , SingleProducts_LowPrice.as_view()),
    path('single_products_with_discount' , SingleProducts_WithDiscount.as_view()),


]

if settings.DEBUG:
    urlpatterns=urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tmart_Product/urls.py
from django.urls import path
from tmart_Product.views import (
    AllProducts,
    ProductSearch,
    SelectedSet,
    ProductDetail,
    AllProductsBy_SubCategory,
    SelectedCategory,
)
# REST
app_name = 'tmart_Product'
urlpatterns = [
    path('set/' , AllProducts.as_view() , name = 'AllProducts'),
    path('set/<int:id>' , SelectedSet.as_view() , name = 'set_with_id'),
    path('category/<int:id>' , SelectedCategory.as_view() , name = 'category_with_id'),
    path('search' , ProductSearch.as_view() , name = 'search'),
    path('ProductDetail/<slug>' , ProductDetail , name = 'ProductDetail'),
    path('subcategory/<int:id>' , AllProductsBy_SubCategory.as_view() , name = 'SubCategory'),
]

tmart_sliders/models.py
from django.db import models
from django.utils.html import format_html
from tmart_Product.models import Set
# Create your models here.

class MainBigSlider(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null= True , blank= True)
    image = models.ImageField(upload_to = 'BigSlider/')
    link_to_set = models.ForeignKey(Set , on_delete = models.CASCADE , blank=True , null = True)
    button_text = models.CharField(max_length=50)
    activate = models.BooleanField(default=False)
    def image_tag(self):
        return format_html('<img src="{}" / style="width:70px;">'.format(self.image.url))
    image_tag.short_description = 'Image'

tmart_sliders/templates/MainBigSlider.html
{% for item in MainSlider %}
           <div class="slide slider__full--screen slider-height-inherit slider-text-right" style="background: rgba(0, 0, 0, 0) url({{item.image.url}}) no-repeat scroll center center / cover ;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-lg-8 col-md-offset-2 col-lg-offset-4 col-sm-12 col-xs-12">
                            <div class="slider__inner">
                                <h2 class="rtl">{{item.title}} <span class="text--theme"></span></h2>
                                <p class="rtl">{{item.description}}</p>
                                <div class="slider__btn">
                                    <a class="htc__btn rtl" href="{{item.link_to_set.get_absolute_url}}">{{item.button_text}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endfor %}

tmart_sliders/templates/common_slider.html
{% load static %}
{% if qs %}
<section class="htc__product__area bg__white ptb--100">
    {% if user_title %}
    <div class="container">
        <hr>
        <h4 class="rtl">{{user_title}}</h4>
    </div>
{% endif %}
{% if random_four_set is not None %}
<div class="container bg__white">
    <div class="main-container">
        <div class="row">
            <div class="cards rtl">
                {% for item in random_four_set %}
                    {% include 'Category_component.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container bg__white">
    <div class="main-container">
        <div class="row">
            <div class="cards rtl">
                {% for item in random_sets %}
                    {% include 'Category_component.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}

{% if random_four_subcategory  %}
<div class="container bg__white">
    <div class="main-container">
        <div class="row">
            <div class="cards rtl">
                {% for item in random_four_subcategory %}
                    {% include 'Category_component.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% elif random_subcategories %}
<div class="container bg__white">
    <div class="main-container">
        <div class="row">
            <div class="cards rtl">
                {% for item in random_subcategories %}
                    {% include 'Category_component.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}


            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="product-categories-all">
                            <div class="product-categories-title">
                                <h3>{{category.name}}</h3>
                            </div>
                            <div class="product-categories-menu">
                                <ul>
                                    {% if category %}
                                        {% for item in category.subcategory.all %}

                                            {% for i in item.set.all|slice:":2" %}
                                                <li><a href="{% url 'tmart_Product:set_with_id' id=i.id %}">{{i.title_fa}}</a></li>
                                            {% endfor %}
                                        
                                        {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="product-style-tab">
                            <div class="product-tab-list">
                                <!-- Nav tabs -->
                                <ul class="tab-style" role="tablist">

                                    <li class="active">
                                        <a href="" data-toggle="tab">
                                            <div class="tab-menu-text">
                                                <h4>{{title}}</h4>
                                            </div>
                                        </a>
                                    </li>
                                        
                                </ul>
                            </div>
                            <div class="tab-content another-product-style jump">
                                <div class="tab-pane active" id="home1">
                                    <div class="row">
                                        <div class="product-slider-active owl-carousel">
                                            {% for item in qs %}
                                            {% include 'slider_product_component.html' %}
                                        </div>
                                            {% endfor %}
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        

            {% for item in qs %}
                {% include 'Products_templates/quick_view.html' %}
            {% endfor %}
        </section>
{% endif %}

tmart_sliders/templates/slider_product_component.html
<div class="col-md-4 single__pro col-lg-4 cat--1 col-sm-4 col-xs-12">
        <div class="product">
            <div class="product__inner">
                    <div class="pro__thumb">
                        <a href="{{item.get_absolute_url}}">
                            <img src="{{item.image.url}}" alt="product images">
                        </a>
                    </div>
            <div class="product__hover__info">
                <ul class="product__action">
                    <li><a data-toggle="modal" data-target="#productModal{{item.id}}" title="Quick View" class="quick-view modal-view detail-link" href="#"><span class="ti-plus"></span></a></li>
                    <li><a title="Wishlist" href="{% url 'add_to_favorite' slug=item.slug %}"><span class="ti-heart"></span></a></li>
                </ul>
            </div>
        </div>
        <div class="product__details">
            <h2><a href="{{item.get_absolute_url}}">{{item.title|truncatewords:6}}</a></h2>
                {% if item.discount > 0 %}
            <ul class="product__price">
                <li class="old__price">{{item.price}}</li>
                <li class="new__price">{{item.price_with_discount}}</li>
            </ul>
                {% else %}
            <ul class="product__price">
                <li class="new__price">{{item.price}}</li>
            </ul>
            {% endif %}
        </div>
    </div>